import { StyleSheet } from 'react-native';
import { ThemeColors } from '../theme/types';

export const createStyles = (theme: ThemeColors) => StyleSheet.create({
    container: {
        flex: 1,
        // backgroundColor: theme.background, // Handled by LinearGradient
    },
    scrollView: {
        flex: 1,
    },
    header: {
        paddingHorizontal: 24,
        paddingVertical: 12,
        // flex: 1,
        // flexDirection: 'row',
        // justifyContent: 'space-between',
        // alignItems: 'center',
        // backgroundColor: theme.surface, // Removed for gradient flow
        // borderBottomWidth: 1,
        // borderBottomColor: theme.border,
    },
    headerTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 24,
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: theme.card,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 4,
    },
    clientInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        // justifyContent: 'space-between',
        backgroundColor: theme.card,
        padding: 6,
        borderRadius: 24,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 1,
        borderColor: theme.border,
        marginBottom: 0,
        // marginBottom: 24,
    },
    avatar: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: theme.borderLight,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    clientDetails: {
        flex: 1,
    },
    clientName: {
        fontSize: 14,
        fontWeight: '700',
        color: theme.text,
        marginBottom: 2,
        letterSpacing: 0.5,
    },
    agencyName: {
        fontSize: 10,
        color: theme.textSecondary,
        fontWeight: '500',
    },
    statusBadge: {
        paddingHorizontal: 16,
        paddingVertical: 4,
        borderRadius: 20,
        backgroundColor: theme.card,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,

    },
    statusText: {
        fontSize: 12,
        fontWeight: '700',
        color: theme.textSecondary,
    },
    jobMeta: {
        backgroundColor: theme.card,
        padding: 14,
        borderRadius: 24,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.12,
        shadowRadius: 16,
        elevation: 8,
        borderWidth: 1,
        borderColor: theme.border,
    },
    metaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    metaText: {
        fontSize: 15,
        color: theme.text,
        marginLeft: 12,
        fontWeight: '500',
    },
    noteText: {
        fontSize: 14,
        color: theme.text,
        // marginTop: 12,
        // fontStyle: 'italic',
        lineHeight: 20,
    },
    section: {
        paddingHorizontal: 24,
        marginBottom: 10,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    sectionTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: theme.text,
    },
    // Status Styles
    statusPending: {
        backgroundColor: '#FFF3E0',
    },
    statusInProgress: {
        backgroundColor: '#E3F2FD',
    },
    statusCompleted: {
        backgroundColor: '#E8F5E9',
    },
    textPending: {
        color: '#EF6C00',
    },
    textInProgress: {
        color: '#1565C0',
    },
    textCompleted: {
        color: '#2E7D32',
    },
    // Input Styles
    inputRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 16,
    },
    inputContainer: {
        flex: 1,
    },
    inputGroup: {
        marginBottom: 16,
    },
    inputLabel: {
        fontSize: 14,
        color: theme.textSecondary,
        marginBottom: 8,
        fontWeight: '600',
    },
    input: {
        borderWidth: 1,
        borderColor: theme.border,
        borderRadius: 16,
        padding: 10,
        fontSize: 16,
        color: theme.text,
        backgroundColor: theme.card,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    // Task Styles
    taskItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
        backgroundColor: theme.card,
        padding: 16,
        borderRadius: 16,
        shadowColor: theme.shadow,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        borderWidth: 1,
        borderColor: theme.border,
    },
    checkbox: {
        width: 24,
        height: 24,
        borderWidth: 2,
        borderColor: theme.textSecondary,
        borderRadius: 8,
        marginRight: 16,
        justifyContent: 'center',
        alignItems: 'center',
    },
    checkboxChecked: {
        backgroundColor: theme.primary,
        borderColor: theme.primary,
    },
    taskText: {
        fontSize: 16,
        color: theme.text,
        flex: 1,
        fontWeight: '500',
    },
    signatureBox: {
        height: 120,
        borderWidth: 2,
        borderColor: theme.border,
        borderStyle: 'dashed',
        borderRadius: 20,
        marginTop: 8,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: theme.card,
    },
    // Action Buttons
    actionButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        marginTop: 12,
        gap: 16,
        marginBottom: 50,
        marginHorizontal: 24,
    },
    checkInButton: {
        flex: 1,
        backgroundColor: theme.primary,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    checkInButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    cancelButton: {
        flex: 1,
        backgroundColor: theme.error,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.error,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    cancelButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    checkOutButton: {
        flex: 1,
        backgroundColor: theme.warning,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.warning,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 4,
    },
    checkOutButtonText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    disabledButton: {
        flex: 1,
        backgroundColor: theme.textTertiary,
        shadowOpacity: 0,
        elevation: 0,
        paddingVertical: 16,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.primary,
        shadowOffset: { width: 0, height: 4 },
        // flex: 1,
        shadowRadius: 8,

    },
    privateKmsSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 16,
        // marginBottom: 16,
        marginHorizontal: 24,
    },
});
